// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Order_Core2.Models;

namespace Order_Core2.Migrations
{
    [DbContext(typeof(DBMYBLOGAPIContext))]
    partial class DBMYBLOGAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Order_Core2.Models.CreateDB.User_Login", b =>
                {
                    b.Property<int>("User_Login_ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("User_Login_CreatDT")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("User_Login_EmailAddress")
                        .HasColumnType("varchar(200)");

                    b.Property<Guid>("User_Login_Guid")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("User_Login_Name")
                        .HasMaxLength(20);

                    b.Property<string>("User_Login_PassWord")
                        .HasMaxLength(20);

                    b.Property<int>("User_Login_Right");

                    b.Property<string>("User_Login_Sex")
                        .HasMaxLength(5);

                    b.Property<bool>("User_Login_State");

                    b.HasKey("User_Login_ID");

                    b.ToTable("User_Login");

                    b.HasData(
                        new { User_Login_ID = 1, User_Login_CreatDT = new DateTime(2018, 7, 15, 23, 11, 34, 10, DateTimeKind.Local), User_Login_EmailAddress = "2351592225@qq.com", User_Login_Guid = new Guid("6c8d25ff-0a0e-4377-9f99-4737e1784d27"), User_Login_Name = "Administrator", User_Login_PassWord = "Administrator", User_Login_Right = 0, User_Login_Sex = "男", User_Login_State = false }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
